root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./bin/web"
  cmd = "(cd ./app/web && swag init --parseDependency) && sqlc generate && templ generate && make app/sqlcore/run && npx tailwindcss -i ./app/web/static/input.css -o ./app/web/static/output.css --minify && make app/web/build"
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "app/web/static", "app/web/docs", "core/models", "extern/db/psql/dal"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "templ", "sql"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

